site_name: zenpyre
site_url: 'https://durandtibo.github.io/zenpyre/'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
    - content.code.select
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  custom_dir: overrides

nav:
  - Home: index.md
  - get_started.md
  - Reference:
      - refs/agents.md
      - refs/chat_models.md
      - refs/data_processors.md
      - refs/document_loaders.md
      - refs/document_stores.md
      - refs/documents.md
      - refs/embeddings.md
      - refs/ingestors.md
      - refs/record_stores.md
      - refs/records.md
      - refs/runnables.md
      - refs/testing.md
      - refs/text_splitters.md
      - refs/utils.md
      - refs/vectorstores.md
  - GitHub: https://github.com/durandtibo/zenpyre

repo_url: https://github.com/durandtibo/zenpyre
repo_name: durandtibo/zenpyre

markdown_extensions:
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - search
  - autorefs:
      resolve_closest: true
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ ../src ]
          options:
            allow_inspection: true
            docstring_style: google
            separate_signature: true
            show_bases: true
            show_object_full_path: true
            show_root_full_path: true
            show_root_heading: true
            show_root_toc_entry: true
            show_signature: true
            show_signature_annotations: true
            show_source: false
            signature_crossrefs: true

extra:
  version:
    method: mike

copyright: Copyright &copy; 2026 - present Thibaut Durand
