name: Cyclic Imports
on:
  workflow_call:
  workflow_dispatch:  # to trigger manually

permissions:
  contents: read

jobs:
  cyclic-import:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v7

      - name: Setup python environment
        uses: durandtibo/setup-venv-uv-action@v0.0.3

      - name: check zenpyre
        run: |
          python -c "import zenpyre"

      - name: check zenpyre.document_loaders
        run: |
          python -c "from zenpyre import document_loaders"
          python -c "from zenpyre.document_loaders import factory"

      - name: check zenpyre.embeddings
        run: |
          python -c "from zenpyre import embeddings"
          python -c "from zenpyre.embeddings import factory"

      - name: check zenpyre.hashing
        run: |
          python -c "from zenpyre import hashing"

      - name: check zenpyre.testing
        run: |
          python -c "from zenpyre import testing"

      - name: check zenpyre.text_splitters
        run: |
          python -c "from zenpyre import text_splitters"
          python -c "from zenpyre.text_splitters import factory"

      - name: check zenpyre.utils
        run: |
          python -c "from zenpyre import utils"
          python -c "from zenpyre.utils import fallback"
          python -c "from zenpyre.utils import imports"
          python -c "from zenpyre.utils import rich"

      - name: check zenpyre.vectorstores
        run: |
          python -c "from zenpyre import vectorstores"
          python -c "from zenpyre.vectorstores import factory"
